### ISSUE TITLE
Move this project to scala/vscode-scala

### ISSUE THREAD

**Issue by nicolasstucki** [nicolasstucki/vscode-scala#1]
We should fork it in https://github.com/scala.

**Comment by nicolasstucki** [comment]
@adriaanm could you help me with this? And add @smarter and me to this fork of the project.

**Comment by nicolasstucki** [comment]
The aim of this move is to force GitHub to use our template to be able to add highlighting fixes and improvements.

**Comment by adriaanm** [comment]
I forked it and made you admin. I seem to remember there's also an actual "move" operation, but that should probably be initiated by the original creator? Anyway, forking is good enough, I assume.

**Comment by nicolasstucki** [comment]
Yes, I would be the one who would need to do the move. But for that, I would also need admin access to https://github.com/scala which is too much. Therefore the fork is perfect.

**Comment by adriaanm** [comment]
I don't mind making you an admin at scala, even if temporarily. I didn't realize you could also do the move.

**Comment by smarter** [comment]
I think it would be much clearer for the non-forked repo to be on scala/

**Comment by smarter** [comment]
It might also make sense to call it vscode-scala-syntax to make its purpose clear.

**Comment by adriaanm** [comment]
Ok, @smarter, I made you an admin. Please go ahead and clean up my mess :-)

**Comment by smarter** [comment]
@adriaanm I'm offline for the next two weeks, better to put @nicolasstucki in charge :).

**Comment by nicolasstucki** [comment]
@adriaanm to make it non-forked I had to delete the repo and create a new one from scratch. Could you recreate the repo `scala/vscode-scala-syntax` and add me as admin again?

**Comment by adriaanm** [comment]
done
